### ISSUE TITLE
When I finished the installation and ran the Stand-alone testing, I encountered a problem：“undefined symbol: SAVER_MODE”

### ISSUE THREAD

**Issue by changjiangbailang** [LatticeX-Foundation/Rosetta#15]
![image](https://user-images.githubusercontent.com/11187356/80612941-339ab000-8a6f-11ea-8a61-80424e9e3a27.png)

**Comment by changjiangbailang** [comment]
when I running “python3 millionaire.py --party_id=0"

**Comment by vingstar** [comment]
It seems strange, and maybe caused by your local system environment. 
Please try the following steps:
1, make sure you have the latest code;
2, and run `./clean_directory.sh && ./clean_pip.sh`  in the top directory of this repository to uninstall the dubious one.
3. run `bash compile_and_test_all.sh` to reinstall a clear and latest Rosetta package.
4. check your tests again.

Please let me know if this dose not work for you.

**Comment by vingstar** [comment]
Dear @changjiangbailang ,
After installation, you may also check whether the library is linked correctly by running `ldd build/lib/libtf-mpcop.so` and you should see that its linkage to libmpc-op.so and libmpc-io.so is within this same source:
![image](https://user-images.githubusercontent.com/3355765/80675738-d5f67a00-8ae7-11ea-9f1f-ceefdc52449e.png)
If it's not linked within this library，you should set the environment variable manually, such as `export LD_LIBRARY_PATH=LD_LIBRARY_PATH:'the_path_to_your_rosetta_code'/build/lib‘

**Comment by changjiangbailang** [comment]
Thanks , it works !
