### ISSUE TITLE
Several questions on Rosetta mode saving and loading to predict

### ISSUE THREAD

**Issue by LaynePeng** [LatticeX-Foundation/Rosetta#43]
I have a little confuse on Rosetta model saving and using:

As the tutorials document describing, the model can be saved as cipher text or plain text, 
Q1. If I save the model as cipher text, and use it to predict with Rosetta. Do all parties in the prediction process require the SAME cipher key used in the training process?
Q2. Can a model trained with normal Tensorflow, but for protecting the data sent to predict, we use Rosetta encrypted the data sent to predict, and reveal the result send back?
Q3. Let say there are a 3-parties training, and the parties of P1 and P2 save as cipher text while P3 plain text. Is there any risk of spy into the original data of P1 and P2 from P3's plain text model?

**Comment by vingstar** [comment]
Hi Layne,
> Q1. If I save the model as cipher text, and use it to predict with Rosetta. Do all parties in the prediction process require the SAME cipher key used in the training process?

No.
In the current version, the security protocol we use is based on **secret sharing**  mechanism.  So there is no so-called  `cipher key` in this protocol itself.  The way to recover plaintext data is to collect enough pieces of ciphertext `share`s.

>  Q2. Can a model trained with normal Tensorflow, but for protecting the data sent to predict, we use Rosetta encrypted the data sent to predict, and reveal the result send back?

 The use case you described seems to be secure computation outsourcing. Just as aforesaid, the current protocol is backed with **secret sharing**  mechanism, a typical approach of Multi-Party Computation.  If your goal is to offload local computation, it is better to secured your application with **homomorphic encryption** technology.  In the near future, Rosetta will also integrate  **homomorphic encryption** technology. 

> Q3. Let say there are a 3-parties training, and the parties of P1 and P2 save as cipher text while P3 plain text. Is there any risk of spy into the original data of P1 and P2 from P3's plain text model?

The security model of the underlying MPC protocol can make sure that in the training process, there is nothing about the original data any party can learn from in the practical sense.  But it is NOT the goal of MPC to ensure the PLAIN output leak nothing about the original input data. It depends on your AI model whether and what the output can reveal about the input data.

Please correct me if I have any misunderstanding about your issue.

**Comment by LaynePeng** [comment]
> No.
> In the current version, the security protocol we use is based on secret sharing mechanism. So there is no so-called cipher key in this protocol itself. The way to recover plaintext data is to collect enough pieces of ciphertext shares.

I am not quite familiar with secret sharing. According to [Model Saving](https://github.com/LatticeX-Foundation/Rosetta/blob/master/doc/TUTORIALS.md#model-saving), if the model save the cipher text, it need to inference with Rosetta. Does it a "share" used in training, need to used when I did inference? How I save this piece of "share"?

> The use case you described seems to be secure computation outsourcing. Just as aforesaid, the current protocol is backed with secret sharing mechanism, a typical approach of Multi-Party Computation. If your goal is to offload local computation, it is better to secured your application with homomorphic encryption technology. In the near future, Rosetta will also integrate homomorphic encryption technology.

No. Suppose this case: we are usually asked to submit the "Windows" or "Office" usage logs to help improve their product. Right? Can we do this: there is a trained model already in Microsoft's servers, and it serves there. I submitted the "private" data to it, and get the opt. suggestion (predict result) sent back to my PC as cipher text. Then I can decrypt the cipher text locally and get the plain opt. suggestion? If we can do this, my software get the opt. without leaking the privacy even to Microsoft.

**Comment by vingstar** [comment]
> Does it a "share" used in training, need to used when I did inference? How I save this piece of "share"?

Do you mean you want to continue to carry out secure inference  task with the learned ciphertext model?  If this is the case, just set `SAVER_MODE=0` in your Rosetta config file when training, and this will make sure every training participant will output a local `share` piece of the learned model.  And after training, the same participants can continue to load their local `share`  and predict on new data with this model securely. 
We will submit a sample code to show this case as soon as possible.

> No. Suppose this case: we are usually asked to submit the "Windows" or "Office" usage logs to help improve their product. Right? Can we do this: there is a trained model already in Microsoft's servers, and it serves there. I submitted the "private" data to it, and get the opt. suggestion (predict result) sent back to my PC as cipher text. Then I can decrypt the cipher text locally and get the plain opt. suggestion? If we can do this, my software get the opt. without leaking the privacy even to Microsoft.

Well, Rosetta definitely support this. In the typical setting you described, you can image the 'user' as `P0` and 'server' as `P1`, while the 'private' data and ''private trained model'  just corresponding to the private matrices in our [demo example](https://github.com/LatticeX-Foundation/Rosetta/blob/master/README.md#usage),  and at last you can set the last parameter of `SecureReveal` as 1 so that only `P0` (the user), rather than `P1`  (Miscrosoft in your example), can get the plain-text opt. 
It is worth mentioning that unlike HE, in most MPC protocols all participants should be 'online' and interactive with each other to perform the computation task together.

P.S.: you can also contact us in our [slack channel](https://join.slack.com/t/latticexrosetta/shared_invite/zt-dum6j65d-MTxp~Bxq5OwouJW8zUKB1Q) to have real-time discussion.

**Comment by vingstar** [comment]
Hi @LaynePeng, I will close this one. If you have any more problems about this one, please  contact us.
